export const SUBMIT_STOCK_ORDER = "SUBMIT_STOCK_ORDER";
export const SUBMIT_STOCK_ORDER_ERROR = "SUBMIT_STOCK_ORDER_ERROR";
export const SUBMIT_STOCK_ORDER_SUCCESS = "SUBMIT_STOCK_ORDER_SUCCESS";
export const RESET_STOCK_STATE = "RESET_STOCK_STATE";

export const SEND_DEPT_ORDER = "SEND_DEPT_ORDER";
export const SEND_DEPT_ORDER_ERROR = "SEND_DEPT_ORDER_ERROR";
export const SEND_DEPT_ORDER_SUCCESS = "SEND_DEPT_ORDER_SUCCESS";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";

export const GET_TEST_LIST = "GET_TEST_LIST";
export const GET_TEST_LIST_SUCCESS = "GET_TEST_LIST_SUCCESS";
export const GET_TEST_LIST_ERROR = "GET_TEST_LIST_ERROR";

export const GET_BATCH_LIST = "GET_BATCH_LIST";
export const GET_BATCH_LIST_SUCCESS = "GET_BATCH_LIST_SUCCESS";
export const GET_BATCH_LIST_ERROR = "GET_BATCH_LIST_ERROR";

export const GET_TEST = "GET_TEST";
export const GET_TEST_ERROR = "GET_TEST_ERROR";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";

export const SEND_CREATED_TEST = "SEND_CREATED_TEST";
export const SEND_CREATED_TEST_SUCCESS = "SEND_CREATED_TEST_SUCCESS";
export const SEND_CREATED_TEST_ERROR = "SEND_CREATED_TEST_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const NOTIFY_SUCCESS = "NOTIFY_SUCCESS";
export const NOTIFY_ERROR = "NOTIFY_ERROR";
export const NOTIFY_LOADING = "NOTIFY_LOADING";
export const NOTIFY_CLEAR = "NOTIFY_CLEAR";

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ALL_QUESTIONS_ERROR = "GET_ALL_QUESTIONS_ERROR";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS";

export const CREATE_QUES = "CREATE_QUES";
export const CREATE_QUES_SUCCESS = "CREATE_QUES_SUCCESS";
export const CREATE_QUES_ERROR = "CREATE_QUES_ERROR";

export const DELETE_QUES="DELETE_QUES";
export const DELETE_QUES_SUCCESS="DELETE_QUES_SUCCESS";
export const DELETE_QUES_ERROR="DELETE_QUES_ERROR";

export const UPDATE_QUES="UPDATE_QUES";
export const LOAD_UPDATED_QUES="LOAD_UPDATED_QUES";

export const GET_ALL_RESULTS="GET_ALL_RESULTS";
export const GET_ALL_RESULTS_ERROR="GET_ALL_RESULTS_ERROR";
export const GET_ALL_RESULTS_SUCCESS="GET_ALL_RESULTS_SUCCESS";