export const SUBMIT_STOCK_ORDER = "SUBMIT_STOCK_ORDER";
export const SUBMIT_STOCK_ORDER_ERROR = "SUBMIT_STOCK_ORDER_ERROR";
export const SUBMIT_STOCK_ORDER_SUCCESS = "SUBMIT_STOCK_ORDER_SUCCESS";
export const RESET_STOCK_STATE = "RESET_STOCK_STATE";

export const SEND_DEPT_ORDER = "SEND_DEPT_ORDER";
export const SEND_DEPT_ORDER_ERROR = "SEND_DEPT_ORDER_ERROR";
export const SEND_DEPT_ORDER_SUCCESS = "SEND_DEPT_ORDER_SUCCESS";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";

export const GET_TEST_LIST = "GET_TEST_LIST";
export const GET_TEST_LIST_SUCCESS = "GET_TEST_LIST_SUCCESS";
export const GET_TEST_LIST_ERROR = "GET_TEST_LIST_ERROR";

export const GET_BATCH_LIST = "GET_BATCH_LIST";
export const GET_BATCH_LIST_SUCCESS = "GET_BATCH_LIST_SUCCESS";
export const GET_BATCH_LIST_ERROR = "GET_BATCH_LIST_ERROR";

export const GET_TEST = "GET_TEST";
export const GET_TEST_ERROR = "GET_TEST_ERROR";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const NOTIFY_SUCCESS = "NOTIFY_SUCCESS";
export const NOTIFY_ERROR = "NOTIFY_ERROR";
export const NOTIFY_LOADING = "NOTIFY_LOADING";
export const NOTIFY_CLEAR = "NOTIFY_CLEAR";

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ALL_QUESTIONS_ERROR = "GET_ALL_QUESTIONS_ERROR";
export const GET_ALL_QUESTIONS_SUCCESS = "GET_ALL_QUESTIONS_SUCCESS";