export const GET_VENDORS = 'GET_VENDORS';
export const GET_VENDORS_ERROR = 'GET_VENDORS_ERROR';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';

export const ADD_VENDOR = 'ADD_VENDOR';
export const ADD_VENDOR_ERROR = 'ADD_VENDOR_ERROR';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';

export const EDIT_VENDOR = 'EDIT_VENDOR';
export const EDIT_VENDOR_ERROR = 'EDIT_VENDOR_ERROR';
export const EDIT_VENDOR_SUCCESS = 'EDIT_VENDOR_SUCCESS';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const SUBMIT_STOCK_ORDER = 'SUBMIT_STOCK_ORDER';
export const SUBMIT_STOCK_ORDER_ERROR = 'SUBMIT_STOCK_ORDER_ERROR';
export const SUBMIT_STOCK_ORDER_SUCCESS = 'SUBMIT_STOCK_ORDER_SUCCESS';
export const RESET_STOCK_STATE = 'RESET_STOCK_STATE';

export const GET_DEPT_LIST = 'GET_DEPT_LIST';
export const GET_DEPT_LIST_ERROR = 'GET_DEPT_LIST_ERROR';
export const GET_DEPT_LIST_SUCCESS = 'GET_DEPT_LIST_SUCCESS';

export const SEND_DEPT_ORDER = 'SEND_DEPT_ORDER';
export const SEND_DEPT_ORDER_ERROR = 'SEND_DEPT_ORDER_ERROR';
export const SEND_DEPT_ORDER_SUCCESS = 'SEND_DEPT_ORDER_SUCCESS';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const GET_INVENTORY_LIST = 'GET_INVENTORY_LIST';
export const GET_INVENTORY_LIST_ERROR = 'GET_INVENTORY_LIST_ERROR';
export const GET_INVENTORY_LIST_SUCCESS = 'GET_INVENTORY_LIST_SUCCESS';


export const ADD_DEPT = 'ADD_DEPT';
export const ADD_DEPT_SUCCESS = 'ADD_DEPT_SUCCESS';
export const ADD_DEPT_ERROR = 'ADD_DEPT_ERROR';

export const EDIT_DEPT = 'EDIT_DEPT';
export const EDIT_DEPT_ERROR = 'EDIT_DEPT_ERROR';
export const EDIT_DEPT_SUCCESS = 'EDIT_DEPT_SUCCESS';


export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';

export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_ERROR = 'NOTIFY_ERROR';
export const NOTIFY_LOADING = 'NOTIFY_LOADING';
export const NOTIFY_CLEAR = 'NOTIFY_CLEAR';

